generated: '2026-07-28'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.westjet.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Feb 16 23:59:59 2027 GMT
  hsts: false
- host: westjetndc.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Jan 27 23:59:59 2027 GMT
  hsts: false
domains:
- domain: westjet.com
  dnssec: false
  caa:
  - 0 issue "entrust.net"
  - 0 issue "amazon.com"
  - 0 issuewild "digicert.com"
  - 0 issue "globalsign.com"
  - 0 issue "sectigo.com"
  - 0 issuewild "globalsign.com"
  spf: true
  dmarc: true
  dmarc_policy: none
- domain: westjetndc.com
  dnssec: false
  caa: []
  spf: true
  dmarc: true
  dmarc_policy: quarantine
